version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: cache
    restart: always
    command: ["redis-server", "--requirepass", "admin"]
    ports:
      - "6379:6379"

  app:
    image: go:latest
    container_name: go_app
    restart: always
    environment:
      POSTGRES_HOST: db              # Use the service name for the host
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: backend
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      IS_DOCKER: "true"
      HTTP_LISTEN_ADDR: "0.0.0.0:3000"
      REDIS_HOST: cache              # Redis connection details
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache

volumes:
  postgres_data:
